name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Target
      run: rustup target add thumbv7m-none-eabi
    - name: Build Library
      run: cargo build --target=thumbv7m-none-eabi --verbose
    - name: Build examples
      run: cargo build --examples --verbose
